# -*- coding: utf-8 -*-
"""Alojamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sp4sKxbP4Lnne-Qz2yWrvXt2Ee_BID45
"""

class Limpiador:
    def __init__(self, nombre, disponible):
        self.nombre = nombre
        self.disponible = disponible

class Contratacion:
    def __init__(self, limpiador):
        self.limpiador = limpiador
        self.confirmada = False

    def confirmar(self):
        if not self.limpiador.disponible:
            return "Error: limpiador no disponible"

        self.confirmada = True
        return f"Contratación confirmada para {self.limpiador.nombre}"

# Ejemplo
limpiador1 = Limpiador("Carlos", True)
contrato = Contratacion(limpiador1)

print(contrato.confirmar())

Public Class Form1

    ' Clase Limpiador
    Public Class Limpiador
        Public Nombre As String
        Public Disponible As Boolean

        Public Sub New(nombre As String, disponible As Boolean)
            Me.Nombre = nombre
            Me.Disponible = disponible
        End Sub
    End Class

    ' Clase Contratación
    Public Class Contratacion
        Public Limpiador As Limpiador
        Public Confirmada As Boolean = False

        Public Sub New(limpiador As Limpiador)
            Me.Limpiador = limpiador
        End Sub

        Public Function Confirmar() As String
            If Limpiador.Nombre = "" Then
                Return "Error: debe ingresar un nombre"
            End If

            If Not Limpiador.Disponible Then
                Return "Error: el limpiador no está disponible"
            End If

            Confirmada = True
            Return "✅ Contratación confirmada para " & Limpiador.Nombre
        End Function
    End Class

    ' Evento del botón
    Private Sub btnConfirmar_Click(sender As Object, e As EventArgs) Handles btnConfirmar.Click

        Dim nombre As String = txtNombre.Text
        Dim disponible As Boolean = chkDisponible.Checked

        Dim limpiador1 As New Limpiador(nombre, disponible)
        Dim contrato As New Contratacion(limpiador1)

        lblResultado.Text = contrato.Confirmar()

    End Sub

End Class