# -*- coding: utf-8 -*-
"""Alojador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Twvb8dRmgBlKpVB1wemJo7aKq9JyDDl
"""

import ipywidgets as widgets
from IPython.display import display

# Lista simulada de limpiadores (re-using from previous cell)
limpiadores = [
    {"nombre": "Carlos Pérez", "experiencia": "2 años"},
    {"nombre": "Ana Gómez", "experiencia": "5 años"},
    {"nombre": "Luis Martínez", "experiencia": "3 años"},
]

# Create a dropdown widget for cleaner selection
limpiador_options = [f"{l['nombre']} - {l['experiencia']}" for l in limpiadores]
cleaner_dropdown = widgets.Dropdown(
    options=limpiador_options,
    description='Selecciona un limpiador:',
    disabled=False,
)

# Create a button for confirmation
confirm_button = widgets.Button(
    description='Confirmar contratación',
    disabled=False,
    button_style='success', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click to confirm',
    icon='check' # (FontAwesome names without the 'fa-' prefix)
)

# Output widget to display messages
output_message = widgets.Output()

# Function to handle button click
def on_confirm_button_clicked(b):
    with output_message:
        output_message.clear_output()
        selected_option = cleaner_dropdown.value

        if not selected_option:
            print("Advertencia: Por favor selecciona un limpiador")
            return

        # Find the selected cleaner object
        selected_cleaner_name = selected_option.split(' - ')[0]
        selected_cleaner = next((l for l in limpiadores if l['nombre'] == selected_cleaner_name), None)

        if selected_cleaner:
            message = f"Has contratado a {selected_cleaner['nombre']} con {selected_cleaner['experiencia']} de experiencia."
            print(f"Confirmación: {message}")
        else:
            print("Error: Limpiador no encontrado.")

# Attach the function to the button click event
confirm_button.on_click(on_confirm_button_clicked)

# Display the widgets
display(cleaner_dropdown, confirm_button, output_message)